#%RAML 1.0 duplication
    responses:
      400:
        description: Bad request.   
        body:
          application/json:
            example:
              {
                message:"Bad request"
              }     
      401:
        description: unauthonticate person.   
        body:
          application/json:
            example:
              {
                message:"You don't have admin privilage"
              }             
      500:
          description: server failer
          body:
            application/json:
              example:
                {
                  message:"server failer"
                }
      404:
          description: not found
          body:
            application/json:
              example:
                {
                  message:"not found"
                }   