#%RAML 1.0 NamedExample
  {
               "productid":113,
               "catagoryid":12,
               "name":"Google home",
               "describtion":"Google home lets you automate staff.it is cool",
               "video_url":"https://www.youtube.com/embed/roiLfAVopIG",
               "price":6000
              }