#%RAML 1.0 NamedExample
 [
   {
              "username":"dawit",
              "userid":1523,
              "orderid":002,
              "email":"dawit@gmail.com"
             }  ,
             {
              "username": "Piter",
              "userid": 1553,
              "orderid": 1515,
              "email": "piter@example.com"
             }
 ]